
name: Terraform Plan & Policy Check

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.7.0

      - name: Terraform fmt
        working-directory: infra/runtime
        run: terraform fmt -check

      - name: Terraform init
        working-directory: infra/runtime
        run: terraform init -input=false

# 2ï¸âƒ£ ðŸ”‘ AWS OIDC â€“ YAHAN ADD KARNA HAI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1
          
      - name: Terraform plan
        working-directory: infra/runtime
        run: terraform plan -out=tfplan

      - name: Convert plan to JSON
        working-directory: infra/runtime
        run: terraform show -json tfplan > plan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: OPA policy check
        run: |
          opa eval \
            --data policies \
            --input infra/runtime/plan.json \
            "data.terraform.policy.deny == []"
