name: Terraform Plan & Policy Check

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@3c1b3d39d0bba8f0d6a6cfa1f1b46a7e27c6d79f
        with:
          terraform_version: 1.7.0

      - name: Ensure runtime directory exists
        run: mkdir -p infra/runtime

      - name: Terraform fmt
        working-directory: infra/runtime
        run: terraform fmt -check || true

      - name: Terraform init
        working-directory: infra/runtime
        run: terraform init -input=false

      - name: Terraform plan
        working-directory: infra/runtime
        run: terraform plan -out=tfplan

      - name: Convert plan to JSON
        working-directory: infra/runtime
        run: terraform show -json tfplan > plan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: OPA policy check
        run: |
          opa eval \
            --data policies \
            --input infra/runtime/plan.json \
            "data.terraform.policy.deny == []"
