name: Terraform GitOps Pipeline

on:
  pull_request:
  push:
    branches: [ "master" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: choice
        options:
          - prod

jobs:
  plan:
    name: Terraform Plan + OPA
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      
    outputs:
      env: ${{ steps.setenv.outputs.env }}

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - name: Determine environment
        id: setenv
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "env=staging" >> $GITHUB_OUTPUT
          else
            echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.7.0

      - name: Terraform fmt
        working-directory: infra/${{ steps.setenv.outputs.env }}
        run: terraform fmt -check

      - name: Terraform init
        working-directory: infra/${{ steps.setenv.outputs.env }}
        run: terraform init -input=false

      # 2ï¸âƒ£ ðŸ”‘ AWS OIDC â€“ YAHAN ADD KARNA HAI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@7474bc4690e29a8392af63c5b98e7449536d5c3a
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ap-south-1

      - name: Terraform plan
        working-directory: infra/${{ steps.setenv.outputs.env }}
        run: terraform plan -out=tfplan

      - name: Convert plan to JSON
        working-directory: infra/${{ steps.setenv.outputs.env }}
        run: terraform show -json tfplan > plan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: OPA policy check
        run: |
          opa eval \
            --data policies \
            --input infra/${{ steps.setenv.outputs.env }}/plan.json \
            "data.terraform.policy.deny == []"

  apply:
    name: Terraform Apply (PROD only)
    needs: plan
    runs-on: ubuntu-latest

    if: |
      github.event_name == 'workflow_dispatch' &&
      needs.plan.outputs.env == 'prod'

    environment: prod

    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd
        with:
          terraform_version: 1.7.0

      - name: Terraform init
        working-directory: infra/prod
        run: terraform init -input=false

      - name: Terraform apply
        working-directory: infra/prod
        run: terraform apply -input=false -auto-approve
