name: Terraform Multi-Env Plan + Policy

on:
  pull_request:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment to run (prod only)"
        required: true
        type: choice
        options: [ prod ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        env: [ dev ]

    steps:
      - uses: actions/checkout@v4

      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Select environment
        id: env
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            echo "env=dev" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "push" ]; then
            echo "env=staging" >> $GITHUB_OUTPUT
          elif [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "env=${{ inputs.environment }}" >> $GITHUB_OUTPUT
          fi

      - name: Terraform fmt
        working-directory: infra/${{ steps.env.outputs.env }}
        run: terraform fmt -check

      - name: Terraform init
        working-directory: infra/${{ steps.env.outputs.env }}
        run: terraform init -input=false

      - name: Terraform plan
        working-directory: infra/${{ steps.env.outputs.env }}
        run: terraform plan -out=tfplan

      - name: Convert plan to JSON
        working-directory: infra/${{ steps.env.outputs.env }}
        run: terraform show -json tfplan > plan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: OPA policy check
        run: |
          opa eval \
            --data policies \
            --input infra/${{ steps.env.outputs.env }}/plan.json \
            "data.terraform.policy.deny == []"
