
name: Terraform Plan & Policy Check

on:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@7fb3960ac6e6da23658d647fdab424c209d11572

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@7fb3960ac6e6da23658d647fdab424c209d11572
        with:
          terraform_version: 1.7.0

      - name: Terraform fmt
        working-directory: infra/runtime
        run: terraform fmt -check

      - name: Terraform init
        working-directory: infra/runtime
        run: terraform init -input=True

      - name: Terraform plan
        working-directory: infra/runtime
        run: terraform plan -out=tfplan

      - name: Convert plan to JSON
        working-directory: infra/runtime
        run: terraform show -json tfplan > plan.json

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/opa

      - name: OPA policy check
        run: |
          opa eval \
            --data policies \
            --input infra/runtime/plan.json \
            "data.terraform.policy.deny == []"
